# pull official base image
FROM node:17.1.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
# RUN npm install
RUN npm ci --silent
# RUN npm install react-scripts@3.4.1 -g --silent

RUN npm run build
# add app
COPY . ./

# start app
CMD ["npm", "start"]
