import { Container, SimpleGrid, useMantineTheme } from '@mantine/core';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useChart } from '../../charts/echarts/useChart';
import ReactEcharts from '../../charts/echarts/ReactEcharts';
import { tradingChartOption } from '../../charts/echarts/StockChartTA';
import { multiChartOptions } from '../../charts/echarts/chartMulti';
import { useCandleChart } from '../../charts/echarts/useCandleChart';

const HomePage: NextPage = () => {
  const { colorScheme } = useMantineTheme();
  const theme = colorScheme === 'dark' ? 'dark' : 'vintage';

  const { ReactCharts: TAChart } = useChart({
    option: tradingChartOption,
    theme,
  });
  const { CandleStickCharts } = useCandleChart({ theme });

  const { ReactCharts: MultiChart, chart: _ } = useChart({
    option: multiChartOptions,
    theme,
  });
  // chart?.showLoading()

  return (
    <>
      <Head>
        <title>Template App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <SimpleGrid style={{ minHeight: '60vh' /* height: 'calc(100vh - 300px)'  */ }} my="lg">
          <ReactEcharts theme={theme} />
        </SimpleGrid>
        <SimpleGrid style={{ minHeight: '60vh' }} my="lg">
          <CandleStickCharts />
        </SimpleGrid>
        <SimpleGrid style={{ minHeight: '60vh' }} my="lg">
          <MultiChart />
        </SimpleGrid>
        <SimpleGrid style={{ minHeight: '60vh' }} my="lg">
          <TAChart />
        </SimpleGrid>
      </Container>
    </>
  );
};

export default HomePage;
