import { Button, useThemeAtom } from "@oyelowo/ui/components";
import { TW, TGrid, TDisplay, cx } from "@oyelowo/ui/tailwind";
import type { NextPage } from "next";
import Head from "next/head";
import { useChart } from "../charts/echarts/ChartWithHooks";
import Link from "next/link";
import ReactEcharts from "../charts/echarts/ReactEcharts";
import { tradingChartOption } from "../charts/echarts/StockChartTA";
import { multiChartOptions } from "../charts/echarts/chartMulti";
import { useCandleChart } from "../charts/echarts/useCandleChart";
import { useEffect } from "react";
// import Box from "../3D/Box";

const Input = () => <input className="border hover:border-red-50 text-red-500" />;

const HomePage: NextPage = () => {
  const [theme, setTheme] = useThemeAtom();
  // const {ReactCharts: CandleStickChart, chart} = useStockCandleCharts();
  const { ReactCharts: CandleChart1 } = useChart({
    option: tradingChartOption,
  });
  // const { ReactCharts: TAChart } = useChart({
  //   option: taChartOption,
  // });
  const { CandleStickCharts } = useCandleChart();
  const { ReactCharts: MultiChart } = useChart({
    option: multiChartOptions,
  });

  useEffect(() => {
    setTheme("dark");
  }, []);

  const k: TGrid | TDisplay = "grid";
  return (
    <>
      <Head>
        <title>Template App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          // minHeight: "100vh",
          width: "98vw",
          justifyContent: "center",
          alignContent: "center",
          alignItems: "center",
          alignSelf: "center",
          margin: "auto",
        }}
      >
        <Button className={["btn-primary", "btn-secondary"]}>
          <Link href="/hello">
            <a>Link to charts</a>
          </Link>
        </Button>
        <br />
        <Link href="/random">
          <a className="text-blue-50">Goto Random Rogue Users</a>
        </Link>
        <br />
        <div className={cx(TW.height("h-96"))}>
          <ReactEcharts />
        </div>
        <br />
        <br />
        <br />
        <div className={cx(TW.height("h-screen"))}>{CandleStickCharts}</div>
        <br />
        <br />
        <br />
        <div className={cx("")} style={{ height: "80vh" }}>
          {MultiChart}
        </div>
        <br />
        <br />
        <br />
        <div className="" style={{ height: "80vh" }}>
          {CandleChart1}
        </div>
        <br />
        <br />
        <br />
        {/* <div className="height[96vh] width[100vw] m-auto">{TAChart}</div> */}
        Home of grind!
        <div className="text-blue-600">
          Separate
          <Input />
          Enter
        </div>
      </main>

      <footer>
        <a href="https://codebreather.com" target="_blank" rel="noopener noreferrer">
          Powered by Code breather
        </a>
      </footer>
    </>
  );
};

export default HomePage;
