import "twin.macro";
import { getLowo, TextField, CardTailWindExample } from "@oyelowo/ui";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Bars, { useChart } from "../charts/echarts/ChartWithHooks";
import Link from "next/link";
import { useQueryClient } from "react-query";
import MyD3Charts from "../charts/d3/App";
import ReactEcharts from "../charts/echarts/ReactEcharts";
import ReactEChartCustom from "../charts/echarts/ChartWithHooks";

// import { useStockCandleCharts } from "../charts/echarts/TradingChart";
import { tradingChartOption } from "../charts/echarts/StockChartTA";
import { taChartOption } from "../charts/echarts/TAChart";
import { multiChartOptions } from "../charts/echarts/chartMulti";
import { useCandleChart } from "../charts/echarts/useCandleChart";
import {
  useCreateUserMutation,
  useGetUsersQuery,
} from "@oyelowo/graphql-client";
import { ReactQueryDevtools } from "react-query/devtools";
import { request, gql, GraphQLClient } from "graphql-request";

const client = new GraphQLClient("http://localhost:8080/graphql", {
  headers: {},
});
const Input = () => <input tw="border hover:border-red-50 text-red-500" />;

const Home: NextPage = () => {
  const queryClient = useQueryClient();
  const { data, isSuccess } = useGetUsersQuery(client);
  const { mutate } = useCreateUserMutation(client, {
    onMutate: () => {
      // queryClient.invalidateQueries(["GetUsers"]);
      queryClient.refetchQueries(["GetUsers"]);
    },
  });
  // const {ReactCharts: CandleStickChart, chart} = useStockCandleCharts();
  const { ReactCharts: CandleChart1 } = useChart({
    option: tradingChartOption,
  });
  // const { ReactCharts: TAChart } = useChart({
  //   option: taChartOption,
  // });
  const { CandleStickCharts } = useCandleChart();
  const { ReactCharts: MultiChart } = useChart({
    option: multiChartOptions,
  });

  // if (!isSuccess) {
  //   return <div>Hasn{"'"}t yet succeeded</div>;
  // }

  return (
    <div tw="bg-black h-screen text-white">
      <Head>
        <title>Template App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main tw="bg-black">
        <h1>The allergy</h1>
        another name {getLowo()} <br />
        <br />
        Create Dummy User
        <button
          tw="text-white"
          onClick={() => {
            mutate({
              userInput: {
                firstName: "Oyelowo" + Math.random(),
                username: "Oyelowo" + Math.random(),
                lastName: "Oyedayo" + Math.random(),
                socialMedia: ["fd"],
                age: 19,
                password: "1234",
                email: +Math.random() + "oye@gmail.com",
              },
            });
          }}
        >
          Crate random user
        </button>
        <ul>
          {data?.users.map((el) => (
            <li key={el.id}>
              <div>First name: {el.firstName}</div>
              <div>Last name: {el.lastName}</div>
              <div>Age: {el.age}</div>
              <div>Social Media: {el.socialMedia.join(", ")}</div>
              <div>Created At: {el.createdAt}</div>
              <div>
                Posts:{" "}
                {el?.posts.map((p, i) => (
                  <div key={i}>
                    <div>Title: {p.title}</div>
                    <div>Content: {p.content}</div>
                  </div>
                ))}
              </div>
            </li>
          ))}
        </ul>
        <br />
        <Link href="/hello">
          <a tw="text-gray-50">Link to charts</a>
        </Link>
        <div tw="height[500px]">
          <ReactEcharts />
        </div>
        <div tw="height[96vh] width[100vw] m-auto">{CandleStickCharts}</div>
        {/* <div tw="height[96vh] width[100vw] m-auto">{TAChart}</div> */}
        <div tw="height[700px]">{MultiChart}</div>
        <div tw="height[700px]">{CandleChart1}</div>
        Home of grind!
        <TextField
          label="Oyelowo Oyedayo"
          description="The sweet field"
          errorMessage="Bad error"
        />
        <CardTailWindExample />
        <div tw="text-blue-600">
          Separate
          <Input />
          Enter
        </div>
      </main>

      <footer>
        <a
          href="https://codebreather.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Code breather
        </a>
      </footer>
    </div>
  );
};

export default Home;
